window.ZORIX_MODEL_INDEX = [
  {
    "id": "nex-coder-38-neptune",
    "name": "Nex Coder 3.8 Preview — Neptune",
    "provider": "Zorix",
    "family": "Nex Coder 3.8",
    "status": "Preview",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 3220000000000,
    "weeklyTokens": 22540000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Nex Coder 3.8 Preview — Neptune is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "deepseek-v4-flash-0731",
    "name": "DeepSeek V4 Flash 0731",
    "provider": "DeepSeek",
    "family": "DeepSeek V4",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/deepseek.svg",
    "color": "#4D6BFE",
    "dailyTokens": 1200000000000,
    "weeklyTokens": 8400000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "DeepSeek V4 Flash 0731 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "tencent-hy3",
    "name": "Tencent Hy3",
    "provider": "Tencent",
    "family": "Hy3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/hunyuan.svg",
    "color": "#00A7CE",
    "dailyTokens": 950000000000,
    "weeklyTokens": 6650000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Tencent Hy3 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "mimo-v25",
    "name": "Xiaomi MiMo-V2.5",
    "provider": "Xiaomi",
    "family": "MiMo",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/mimo.svg",
    "color": "#FF6900",
    "dailyTokens": 150000000,
    "weeklyTokens": 1050000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Xiaomi MiMo-V2.5 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-56-luna",
    "name": "GPT-5.6 Luna",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 310000,
    "weeklyTokens": 2170000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GPT-5.6 Luna is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-56-terra",
    "name": "GPT-5.6 Terra",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#1F4E94",
    "dailyTokens": 0,
    "weeklyTokens": 4580000,
    "weeklyEstimated": false,
    "context": "1.05M tokens",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Closed",
    "inputPrice": "$2 / M tokens",
    "outputPrice": "$12 / M tokens",
    "about": "GPT-5.6 Terra is OpenAI's balanced GPT-5.6 model for workloads that trade off intelligence, speed and cost. OpenAI documents a 1.05M-token context window, a 128K-token maximum output, a Feb 16, 2026 knowledge cutoff and reasoning effort levels from none through max. Zorix Metron currently records two supplied period observations for Terra: 4.58M tokens per week and 72.11B tokens per 30 days. No measured daily Terra series has been published, so these period totals are not converted into a synthetic daily trend.",
    "docs": "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "2026-07-09",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Metron · weekly and 30-day token observations",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": true,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 72110000000,
    "thirtyDayObserved": true,
    "officialModelId": "gpt-5.6-terra",
    "knowledgeCutoff": "Feb 16, 2026",
    "maxOutputTokens": "128K tokens",
    "reasoningEfforts": [
      "none",
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ],
    "cachedInputPrice": "$0.20 / M tokens",
    "chart": []
  },
  {
    "id": "claude-opus-5",
    "name": "Claude Opus 5",
    "provider": "Anthropic",
    "family": "Claude Opus",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 1200000000000,
    "weeklyTokens": 8400000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Opus 5 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "glm-53-flash",
    "name": "GLM 5.3 Flash",
    "provider": "Z.ai",
    "family": "GLM 5",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GLM 5.3 Flash is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "glm-52-max",
    "name": "GLM 5.2 Max",
    "provider": "Z.ai",
    "family": "GLM 5.2",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 314286,
    "weeklyTokens": 2200000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GLM 5.2 Max is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gemini-37-flash",
    "name": "Gemini 3.7 Flash",
    "provider": "Google",
    "family": "Gemini 3.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 414285714,
    "weeklyTokens": 2900000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Gemini 3.7 Flash is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-sonnet-5",
    "name": "Claude Sonnet 5",
    "provider": "Anthropic",
    "family": "Claude Sonnet",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Sonnet 5 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-opus-48",
    "name": "Claude Opus 4.8",
    "provider": "Anthropic",
    "family": "Claude Opus",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 157143,
    "weeklyTokens": 1100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Opus 4.8 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-fable-5-fallback-max",
    "name": "Claude Fable 5 (with fallback max)",
    "provider": "Anthropic",
    "family": "Claude Fable",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Fable 5 (with fallback max) is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-56-sol-max",
    "name": "GPT-5.6 Sol (Max)",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 242857,
    "weeklyTokens": 1700000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GPT-5.6 Sol (Max) is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "kimi-k27-code",
    "name": "Kimi K2.7 Code",
    "provider": "Moonshot AI",
    "family": "Kimi K2.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/kimi.svg",
    "color": "#1783FF",
    "dailyTokens": 157142857143,
    "weeklyTokens": 1100000000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Kimi K2.7 Code is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "kimi-k3",
    "name": "Kimi K3",
    "provider": "Moonshot AI",
    "family": "Kimi K3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/kimi.svg",
    "color": "#1783FF",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Kimi K3 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "nex-coder-37-pro-max",
    "name": "Zorix Nex Coder 3.7 Pro (Max)",
    "provider": "Zorix",
    "family": "Nex Coder 3.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 1500000000000,
    "weeklyTokens": 10500000000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Zorix Nex Coder 3.7 Pro (Max) is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gemini-36-flash",
    "name": "Gemini 3.6 Flash",
    "provider": "Google",
    "family": "Gemini 3.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 12785714286,
    "weeklyTokens": 89500000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Gemini 3.6 Flash is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "muse-spark-12",
    "name": "Muse Spark 1.2",
    "provider": "Meta",
    "family": "Muse Spark",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/meta.svg",
    "color": "#087AEA",
    "dailyTokens": 11130000000,
    "weeklyTokens": 77910000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Muse Spark 1.2 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "glm-51",
    "name": "GLM 5.1",
    "provider": "Z.ai",
    "family": "GLM 5.1",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 271428571,
    "weeklyTokens": 1900000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GLM 5.1 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "nemotron-3-ultra",
    "name": "NVIDIA Nemotron 3 Ultra",
    "provider": "NVIDIA",
    "family": "Nemotron 3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/nvidia.svg",
    "color": "#74B71B",
    "dailyTokens": 6100000000,
    "weeklyTokens": 42700000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "NVIDIA Nemotron 3 Ultra is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Code",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "wolf-theta",
    "name": "Wolf Theta",
    "provider": "Undisclosed",
    "family": "Wolf Theta",
    "status": "Blind test",
    "logo": "/number-of-calls/assets/logos/wolf-theta.svg",
    "color": "#7A8A9A",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "Undisclosed",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "Not published",
    "outputPrice": "Not published",
    "about": "Wolf Theta is a blind-test model alias launched on Aug 31, 2026. Its underlying model is intentionally not disclosed during blind testing. Current published data records a community voting score of 1,553 and a weekly request volume of 87.98B. No token usage or historical request series is published.",
    "docs": "",
    "usageMetric": "requests",
    "weeklyRequests": 87980000000,
    "launchDate": "2026-08-31",
    "underlyingModel": "Not disclosed during blind testing",
    "blindTest": true,
    "source": "Zorix Metron blind-test telemetry",
    "includeInTokenRanking": false,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [
      {
        "id": "english-zorix-like-watermark",
        "language": "English",
        "type": "Output artifact",
        "status": "Unverified",
        "confidence": "Circumstantial",
        "finding": "A third-party observation reports that Wolf Theta output contained a watermark that appeared highly suggestive of Zorix branding.",
        "interpretation": "The observation may indicate a Zorix-related generation, serving, rendering, or evaluation layer. It does not establish the identity of Wolf Theta's underlying model.",
        "verification": "No independently reproducible artifact or provider confirmation has been attached yet."
      },
      {
        "id": "flash-class-behavioral-fingerprint",
        "language": "English",
        "type": "Behavioral fingerprint",
        "status": "Unverified",
        "confidence": "Circumstantial",
        "finding": "Third-party testers reported that Wolf Theta revealed recognizable behavioral characteristics unusually quickly. Based on those observations, they suspect it may belong to a Flash-class model family.",
        "interpretation": "The testers did not characterize Wolf Theta as a frontier-tier model. In their comparative testing, however, they reported that Wolf Theta clearly outperformed Zorix Star Flash 3.5 and Gemini 3.7 Flash.",
        "verification": "The original prompt set, raw outputs and scoring methodology have not been published with this observation. The result remains circumstantial and does not establish Wolf Theta's underlying model.",
        "references": [
          {
            "name": "Zorix Star Flash 3.5",
            "kind": "Official Zorix model reference",
            "availability": "External reference",
            "url": "https://models.zorix.it/"
          },
          {
            "name": "Gemini 3.7 Flash",
            "kind": "Metron comparison model",
            "availability": "Tracked by Metron",
            "url": "/number-of-calls/models/gemini-37-flash/"
          }
        ]
      }
    ],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "hy4-preview",
    "name": "Tencent Hy4 preview",
    "provider": "Tencent",
    "family": "Hy4",
    "status": "Preview",
    "logo": "/number-of-calls/assets/logos/hunyuan.svg",
    "color": "#00A7CE",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "1M tokens",
    "parameters": "770B total",
    "activeParameters": "49B activated",
    "architecture": "Mixture-of-Experts (MoE) · Gated DSA · iHC · native MTP",
    "inputPrice": "$0.834 / M tokens",
    "outputPrice": "$2.501 / M tokens",
    "about": "Tencent Hy4 preview is a next-generation Mixture-of-Experts flagship model from the Tencent Hy Team. Public Tencent material describes a 770B total-parameter backbone with 49B parameters activated per token, Gated DSA sparse attention, iHC residual connections and native MTP speculative decoding. Tencent publicly released and open-sourced Hy4 preview on Aug 28, 2026. Zorix began tracking the model on Sep 1, 2026. The currently published Zorix Metron observation is 17.9B tokens over a five-hour window. No daily, weekly or 30-day Hy4 token total has been published by Zorix.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "launchDate": "2026-09-01",
    "underlyingModel": "",
    "blindTest": false,
    "source": "Zorix Metron · 5-hour token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "fiveHourTokens": 17900000000,
    "fiveHourOnlyTokens": true,
    "providerReleaseDate": "2026-08-28",
    "maxInputTokens": "960K tokens",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "officialModelId": "hy4-preview",
    "knowledgeCutoff": "",
    "maxOutputTokens": "64K tokens",
    "reasoningEfforts": [],
    "cachedInputPrice": "$0.042 / M tokens",
    "chart": []
  }
];
