window.ZORIX_MODEL_INDEX = [
  {
    "id": "nex-coder-38-neptune",
    "name": "Nex Coder 3.8 Preview — Neptune",
    "provider": "Zorix",
    "family": "Nex Coder 3.8",
    "status": "Preview",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 3220000000000,
    "weeklyTokens": 22540000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Nex Coder 3.8 Preview — Neptune is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "deepseek-v4-flash-0731",
    "name": "DeepSeek V4 Flash 0731",
    "provider": "DeepSeek",
    "family": "DeepSeek V4",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/deepseek.svg",
    "color": "#4D6BFE",
    "dailyTokens": 1200000000000,
    "weeklyTokens": 8400000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "DeepSeek V4 Flash 0731 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "tencent-hy3",
    "name": "Tencent Hy3",
    "provider": "Tencent",
    "family": "Hy3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/hunyuan.svg",
    "color": "#00A7CE",
    "dailyTokens": 950000000000,
    "weeklyTokens": 6650000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Tencent Hy3 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "mimo-v25",
    "name": "Xiaomi MiMo-V2.5",
    "provider": "Xiaomi",
    "family": "MiMo",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/mimo.svg",
    "color": "#FF6900",
    "dailyTokens": 150000000,
    "weeklyTokens": 1050000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Xiaomi MiMo-V2.5 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "gpt-56-luna",
    "name": "GPT-5.6 Luna",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 310000,
    "weeklyTokens": 2170000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GPT-5.6 Luna is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "claude-opus-5",
    "name": "Claude Opus 5",
    "provider": "Anthropic",
    "family": "Claude Opus",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 1200000000000,
    "weeklyTokens": 8400000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Opus 5 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "glm-53-flash",
    "name": "GLM 5.3 Flash",
    "provider": "Z.ai",
    "family": "GLM 5",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GLM 5.3 Flash is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "glm-52-max",
    "name": "GLM 5.2 Max",
    "provider": "Z.ai",
    "family": "GLM 5.2",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 314286,
    "weeklyTokens": 2200000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GLM 5.2 Max is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "gemini-37-flash",
    "name": "Gemini 3.7 Flash",
    "provider": "Google",
    "family": "Gemini 3.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 414285714,
    "weeklyTokens": 2900000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Gemini 3.7 Flash is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "claude-sonnet-5",
    "name": "Claude Sonnet 5",
    "provider": "Anthropic",
    "family": "Claude Sonnet",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Sonnet 5 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "claude-opus-48",
    "name": "Claude Opus 4.8",
    "provider": "Anthropic",
    "family": "Claude Opus",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 157143,
    "weeklyTokens": 1100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Opus 4.8 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "claude-fable-5-fallback-max",
    "name": "Claude Fable 5 (with fallback max)",
    "provider": "Anthropic",
    "family": "Claude Fable",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Fable 5 (with fallback max) is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "gpt-56-sol-max",
    "name": "GPT-5.6 Sol (Max)",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 242857,
    "weeklyTokens": 1700000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GPT-5.6 Sol (Max) is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "kimi-k27-code",
    "name": "Kimi K2.7 Code",
    "provider": "Moonshot AI",
    "family": "Kimi K2.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/kimi.svg",
    "color": "#1783FF",
    "dailyTokens": 157142857143,
    "weeklyTokens": 1100000000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Kimi K2.7 Code is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "kimi-k3",
    "name": "Kimi K3",
    "provider": "Moonshot AI",
    "family": "Kimi K3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/kimi.svg",
    "color": "#1783FF",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Kimi K3 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "nex-coder-37-pro-max",
    "name": "Zorix Nex Coder 3.7 Pro (Max)",
    "provider": "Zorix",
    "family": "Nex Coder 3.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 1500000000000,
    "weeklyTokens": 10500000000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Zorix Nex Coder 3.7 Pro (Max) is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "gemini-36-flash",
    "name": "Gemini 3.6 Flash",
    "provider": "Google",
    "family": "Gemini 3.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 12785714286,
    "weeklyTokens": 89500000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Gemini 3.6 Flash is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "muse-spark-12",
    "name": "Muse Spark 1.2",
    "provider": "Meta",
    "family": "Muse Spark",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/meta.svg",
    "color": "#087AEA",
    "dailyTokens": 11130000000,
    "weeklyTokens": 77910000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Muse Spark 1.2 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "glm-51",
    "name": "GLM 5.1",
    "provider": "Z.ai",
    "family": "GLM 5.1",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 271428571,
    "weeklyTokens": 1900000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GLM 5.1 is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  },
  {
    "id": "nemotron-3-ultra",
    "name": "NVIDIA Nemotron 3 Ultra",
    "provider": "NVIDIA",
    "family": "Nemotron 3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/nvidia.svg",
    "color": "#74B71B",
    "dailyTokens": 6100000000,
    "weeklyTokens": 42700000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "NVIDIA Nemotron 3 Ultra is currently listed in Zorix Metron. Usage figures on this page represent traffic recorded inside Zorix Code / Metron.",
    "docs": "",
    "chart": []
  }
];
