window.ZORIX_MODEL_INDEX = [
  {
    "id": "nex-coder-39-alara-preview",
    "name": "Nex Coder 3.9 Alara Preview",
    "provider": "Zorix",
    "family": "Nex Coder 3.9",
    "status": "Internal preview",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#14B87A",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Nex Coder 3.9 Alara Preview is an internal Zorix preview tracked in WebDev community voting. Zorix Metron currently records a supplied 10-hour request observation of 212.1B requests. This request metric is kept separate from token usage and is not converted into tokens. The Alara introduction page publishes only the Ultra internal benchmark preview values against their listed public reference endpoints.",
    "docs": "/nex-coder-39-alara/",
    "usageMetric": "requests",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron · WebDev community voting + supplied 10-hour request observation",
    "includeInTokenRanking": false,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "",
    "thirtyDayPeriodLabel": "",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "nex-coder-38-neptune",
    "name": "Nex Coder 3.8 Preview — Neptune",
    "provider": "Zorix",
    "family": "Nex Coder 3.8",
    "status": "Preview",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 3220000000000,
    "weeklyTokens": 22540000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 77290000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Nex Coder 3.8 Preview Neptune",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "deepseek-v4-flash-0731",
    "name": "DeepSeek V4 Flash 0731",
    "provider": "DeepSeek",
    "family": "DeepSeek V4",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/deepseek.svg",
    "color": "#4D6BFE",
    "dailyTokens": 1200000000000,
    "weeklyTokens": 8400000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 34980000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "DeepSeek V4 Flash 0731",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "tencent-hy3",
    "name": "Tencent Hy3",
    "provider": "Tencent",
    "family": "Hy3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/hunyuan.svg",
    "color": "#00A7CE",
    "dailyTokens": 950000000000,
    "weeklyTokens": 6650000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 26860000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Tencent Hy3",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "mimo-v25",
    "name": "Xiaomi MiMo-V2.5",
    "provider": "Xiaomi",
    "family": "MiMo",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/mimo.svg",
    "color": "#FF6900",
    "dailyTokens": 150000000,
    "weeklyTokens": 1050000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 5920000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Xiaomi MiMo-V2.5",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-56-luna",
    "name": "GPT-5.6 Luna",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 310000,
    "weeklyTokens": 2170000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 8940000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "GPT-5.6 Luna",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-56-terra",
    "name": "GPT-5.6 Terra",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#1F4E94",
    "dailyTokens": 0,
    "weeklyTokens": 4580000,
    "weeklyEstimated": false,
    "context": "1.05M tokens",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Closed",
    "inputPrice": "$2 / M tokens",
    "outputPrice": "$12 / M tokens",
    "about": "GPT-5.6 Terra is OpenAI's balanced GPT-5.6 model for workloads that trade off intelligence, speed and cost. OpenAI documents a 1.05M-token context window, a 128K-token maximum output, a Feb 16, 2026 knowledge cutoff and reasoning effort levels from none through max. Zorix Metron currently records two supplied period observations for Terra: 4.58M tokens per week and 72.11B tokens per 30 days. No measured daily Terra series has been published, so these period totals are not converted into a synthetic daily trend.",
    "docs": "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-07-09",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron · weekly and 30-day token observations + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": true,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 72110000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "GPT-5.6 Terra",
    "thirtyDayPeriodLabel": "observed 30 days",
    "officialModelId": "gpt-5.6-terra",
    "knowledgeCutoff": "Feb 16, 2026",
    "maxOutputTokens": "128K tokens",
    "reasoningEfforts": [
      "none",
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ],
    "cachedInputPrice": "$0.20 / M tokens",
    "chart": []
  },
  {
    "id": "claude-opus-5",
    "name": "Claude Opus 5",
    "provider": "Anthropic",
    "family": "Claude Opus",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 1200000000000,
    "weeklyTokens": 8400000000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 29580000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Claude Opus 5",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "glm-53-flash",
    "name": "GLM 5.3 Flash",
    "provider": "Z.ai",
    "family": "GLM 5",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 8210000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "GLM 5.3 Flash",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "glm-52-max",
    "name": "GLM 5.2 Max",
    "provider": "Z.ai",
    "family": "GLM 5.2",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 314286,
    "weeklyTokens": 2200000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 8580000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "GLM 5.2 Max",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gemini-37-flash",
    "name": "Gemini 3.7 Flash",
    "provider": "Google",
    "family": "Gemini 3.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 414285714,
    "weeklyTokens": 2900000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 7110000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Gemini 3.7 Flash",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-sonnet-5",
    "name": "Claude Sonnet 5",
    "provider": "Anthropic",
    "family": "Claude Sonnet",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 8060000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Claude Sonnet 5",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-opus-48",
    "name": "Claude Opus 4.8",
    "provider": "Anthropic",
    "family": "Claude Opus",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 157143,
    "weeklyTokens": 1100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 4220000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Claude Opus 4.8",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-fable-5-fallback-max",
    "name": "Claude Fable 5 (with fallback max)",
    "provider": "Anthropic",
    "family": "Claude Fable",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 8060000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Claude Fable 5 (with fallback max)",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-fable-51",
    "name": "Claude Fable 5.1",
    "provider": "Anthropic",
    "family": "Claude Fable",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 12400000000,
    "weeklyTokens": null,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Fable 5.1 is tracked by Zorix Metron. The currently published Zorix observation is 12.4B tokens over its first one-day launch window on Sep 2, 2026. No weekly or 30-day Fable 5.1 token total is published here, so the one-day observation is not extrapolated into longer periods. Zorix Metron separately records a supplied 10-hour request observation of 176.98B requests. This does not replace or extrapolate the published one-day token observation.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-02",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron · 1-day token observation + Zorix Metron supplied 10-hour request observation + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": true,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 33400000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Claude Fable 5.1",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-56-sol-max",
    "name": "GPT-5.6 Sol (Max)",
    "provider": "OpenAI",
    "family": "GPT-5.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 242857,
    "weeklyTokens": 1700000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 6520000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "GPT-5.6 Sol (Max)",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-6-astra",
    "name": "GPT-6 Astra",
    "provider": "OpenAI",
    "family": "GPT-6",
    "status": "Rolling out",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "1.05M tokens",
    "parameters": "Not disclosed by OpenAI",
    "activeParameters": "Not disclosed by OpenAI",
    "architecture": "Closed · architecture details not disclosed",
    "inputPrice": "$10 / M tokens",
    "outputPrice": "$50 / M tokens",
    "about": "GPT-6 Astra is OpenAI's most capable model for complex reasoning, coding, computer use, research, and end-to-end professional work. OpenAI documents a 1.05M-token context window, a 128K-token maximum output, an Apr 30, 2026 knowledge cutoff, and reasoning effort levels low, medium, high, xhigh, and max. Standard API pricing is $10 per million input tokens and $50 per million output tokens. OpenAI has not published a parameter count or active-parameter count. Zorix Metron tracks WebDev community voting and a separate exact 30-day token observation; token usage is not inferred from request metrics. Zorix Metron separately records a supplied 10-hour request observation of 242.13B requests. Request counts and token counts remain separate metrics.",
    "docs": "https://developers.openai.com/api/docs/models/gpt-6-astra",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-03",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "OpenAI official GPT-6 Astra model documentation + Zorix Metron WebDev community voting + Zorix Metron supplied 10-hour request observation + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-03",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 63400000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "GPT-6 Astra",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "gpt-6-astra",
    "knowledgeCutoff": "Apr 30, 2026",
    "maxOutputTokens": "128K tokens",
    "reasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ],
    "cachedInputPrice": "Separate rate · not listed here",
    "chart": []
  },
  {
    "id": "kimi-k27-code",
    "name": "Kimi K2.7 Code",
    "provider": "Moonshot AI",
    "family": "Kimi K2.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/kimi.svg",
    "color": "#1783FF",
    "dailyTokens": 157142857143,
    "weeklyTokens": 1100000000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 3980000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Kimi K2.7 Code",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "kimi-k3",
    "name": "Kimi K3",
    "provider": "Moonshot AI",
    "family": "Kimi K3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/kimi.svg",
    "color": "#1783FF",
    "dailyTokens": 300000,
    "weeklyTokens": 2100000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 7760000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Kimi K3",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "nex-coder-37-pro-max",
    "name": "Zorix Nex Coder 3.7 Pro (Max)",
    "provider": "Zorix",
    "family": "Nex Coder 3.7",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 1500000000000,
    "weeklyTokens": 10500000000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 43370000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Zorix Nex Coder 3.7 Pro (Max)",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gemini-36-flash",
    "name": "Gemini 3.6 Flash",
    "provider": "Google",
    "family": "Gemini 3.6",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 12785714286,
    "weeklyTokens": 89500000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 367500000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Gemini 3.6 Flash",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "muse-spark-12",
    "name": "Muse Spark 1.2",
    "provider": "Meta",
    "family": "Muse Spark",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/meta.svg",
    "color": "#087AEA",
    "dailyTokens": 11130000000,
    "weeklyTokens": 77910000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 322400000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "Muse Spark 1.2",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "muse-spark-13",
    "name": "Muse Spark 1.3",
    "provider": "Meta",
    "family": "Muse Spark",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/meta.svg",
    "color": "#4B5FD1",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Muse Spark 1.3 is currently represented in Zorix Metron WebDev community voting. No Zorix request-volume observation is published for this model in this entry.",
    "docs": "",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 11400000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Muse Spark 1.3",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "glm-51",
    "name": "GLM 5.1",
    "provider": "Z.ai",
    "family": "GLM 5.1",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 271428571,
    "weeklyTokens": 1900000000,
    "weeklyEstimated": false,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 7820000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "GLM 5.1",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "nemotron-3-ultra",
    "name": "NVIDIA Nemotron 3 Ultra",
    "provider": "NVIDIA",
    "family": "Nemotron 3",
    "status": "Available",
    "logo": "/number-of-calls/assets/logos/nvidia.svg",
    "color": "#74B71B",
    "dailyTokens": 6100000000,
    "weeklyTokens": 42700000000,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 195800000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "NVIDIA Nemotron 3 Ultra",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "wolf-theta",
    "name": "Zorix Star Flash 3.6",
    "provider": "Zorix",
    "family": "Star Flash 3.6",
    "status": "Revealed",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "Undisclosed",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "Not published",
    "outputPrice": "Not published",
    "about": "Zorix Star Flash 3.6 was previously served under the blind-test alias Wolf Theta. Its identity has now been revealed. Zorix Metron records supplied request observations of 4.22T requests over 7 days and 12.15T requests over 30 days. These are exact period observations: they are not normalized into daily traffic, not extrapolated into other windows, and are kept separate from token usage.",
    "docs": "",
    "usageMetric": "requests",
    "weeklyRequests": 4220000000000,
    "thirtyDayRequests": 12150000000000,
    "launchDate": "",
    "underlyingModel": "Zorix Star Flash 3.6",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix identity disclosure + Zorix Metron supplied 7-day and 30-day request observations + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 18700000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Zorix Star Flash",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "hy4-preview",
    "name": "Tencent Hy4 preview",
    "provider": "Tencent",
    "family": "Hy4",
    "status": "Preview",
    "logo": "/number-of-calls/assets/logos/hunyuan.svg",
    "color": "#00A7CE",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "1M tokens",
    "parameters": "770B total",
    "activeParameters": "49B activated",
    "architecture": "Mixture-of-Experts (MoE) · Gated DSA · iHC · native MTP",
    "inputPrice": "$0.834 / M tokens",
    "outputPrice": "$2.501 / M tokens",
    "about": "Tencent Hy4 preview is a next-generation Mixture-of-Experts flagship model from the Tencent Hy Team. Public Tencent material describes a 770B total-parameter backbone with 49B parameters activated per token, Gated DSA sparse attention, iHC residual connections and native MTP speculative decoding. Tencent publicly released and open-sourced Hy4 preview on Aug 28, 2026. Zorix began tracking the model on Sep 1, 2026. The currently published Zorix Metron observation is 17.9B tokens over a five-hour window. No daily, weekly or 30-day Hy4 token total has been published by Zorix.",
    "docs": "",
    "usageMetric": "tokens",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-01",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron · 5-hour token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": 17900000000,
    "fiveHourOnlyTokens": true,
    "providerReleaseDate": "2026-08-28",
    "maxInputTokens": "960K tokens",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "",
    "thirtyDayPeriodLabel": "",
    "officialModelId": "hy4-preview",
    "knowledgeCutoff": "",
    "maxOutputTokens": "64K tokens",
    "reasoningEfforts": [],
    "cachedInputPrice": "$0.042 / M tokens",
    "chart": []
  },
  {
    "id": "gemini-38-flash",
    "name": "Gemini 3.8 Flash",
    "provider": "Google",
    "family": "Gemini 3.8",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Gemini 3.8 Flash is currently represented in Zorix Metron WebDev community voting. No Zorix request-volume observation is published for this model in this entry.",
    "docs": "",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 22500000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Gemini 3.8 Flash",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-opus-55",
    "name": "Claude Opus 5.5",
    "provider": "Anthropic",
    "family": "Claude Opus",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Opus 5.5 is tracked in Zorix Metron WebDev community voting. A community score is published; no request-volume observation is published here, and no request count is inferred.",
    "docs": "https://www.anthropic.com/claude-opus-5-5",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-22",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting; request observation pending + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-22",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 50600000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Claude Opus 5.5",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "claude-mythos-51",
    "name": "Claude Mythos 5.1",
    "provider": "Anthropic",
    "family": "Claude Mythos",
    "status": "Limited access · Pending tracking",
    "logo": "/number-of-calls/assets/logos/anthropic.svg",
    "color": "#D97757",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Claude Mythos 5.1 was announced by Anthropic on Sep 1, 2026 and is offered through trusted-access programs. Zorix Metron has added it to the pending WebDev tracking pool. No community score or request count is inferred before a Zorix observation is supplied.",
    "docs": "https://www.anthropic.com/claude/mythos",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-01",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Anthropic official announcement + Zorix Metron pending vote/request assignment",
    "includeInTokenRanking": false,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-01",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "",
    "thirtyDayPeriodLabel": "",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gpt-6-sol",
    "name": "GPT-6 Sol",
    "provider": "OpenAI",
    "family": "GPT-6",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "1.05M tokens",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "$2 / M tokens",
    "outputPrice": "$10 / M tokens",
    "about": "GPT-6 Sol is tracked in Zorix Metron WebDev community voting. A community score is published; no request-volume observation is published here, and no request count is inferred.",
    "docs": "https://developers.openai.com/api/docs/models",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-22",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting; request observation pending + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-22",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 41900000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "GPT-6 Sol",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "gpt-6-sol",
    "knowledgeCutoff": "Apr 20, 2026",
    "maxOutputTokens": "128K tokens",
    "reasoningEfforts": [
      "none",
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ],
    "cachedInputPrice": "$0.20 / M tokens",
    "chart": []
  },
  {
    "id": "gpt-6-luna",
    "name": "GPT-6 Luna",
    "provider": "OpenAI",
    "family": "GPT-6",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/openai.svg",
    "color": "#111111",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "1.05M tokens",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "$0.10 / M tokens",
    "outputPrice": "$0.50 / M tokens",
    "about": "GPT-6 Luna is tracked in Zorix Metron WebDev community voting. A community score is published; no request-volume observation is published here, and no request count is inferred.",
    "docs": "https://developers.openai.com/api/docs/models/gpt-6-luna",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-22",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting; request observation pending + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-22",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 7200000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "GPT-6 Luna",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "gpt-6-luna",
    "knowledgeCutoff": "May 18, 2026",
    "maxOutputTokens": "128K tokens",
    "reasoningEfforts": [
      "none",
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ],
    "cachedInputPrice": "$0.01 / M tokens",
    "chart": []
  },
  {
    "id": "deepseek-v41-flash",
    "name": "DeepSeek V4.1 Flash",
    "provider": "DeepSeek",
    "family": "DeepSeek V4.1",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/deepseek.svg",
    "color": "#4D6BFE",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "DeepSeek V4.1 Flash is tracked in Zorix Metron WebDev community voting. A community score is published; no request-volume observation is published here, and no request count is inferred.",
    "docs": "https://www.deepseek.com/en/news/deepseek-v4-1-flash/",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-10",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting; request observation pending + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-10",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 14900000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "DeepSeek V4.1 Flash",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "deepseek-flash",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "gemini-38-flash-cyber",
    "name": "Gemini 3.8 Flash Cyber",
    "provider": "Google",
    "family": "Gemini 3.8",
    "status": "Pending tracking",
    "logo": "/number-of-calls/assets/logos/google.svg",
    "color": "#4285F4",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Gemini 3.8 Flash Cyber was announced by Google on Sep 2, 2026 alongside Gemini 3.8 Flash for cybersecurity-oriented agentic workflows. Zorix Metron has added it to the pending WebDev tracking pool. No score or request volume is inferred.",
    "docs": "https://blog.google/innovation-and-ai/models-and-research/gemini-models/3-8-flash-and-3-8-flash-cyber/",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-02",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Google official Gemini 3.8 announcement + Zorix Metron pending vote/request assignment",
    "includeInTokenRanking": false,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-02",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": null,
    "thirtyDayObserved": false,
    "thirtyDayOnlyTokens": false,
    "thirtyDayLabel": "",
    "thirtyDayPeriodLabel": "",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "grok-47",
    "name": "Grok 4.7",
    "provider": "xAI",
    "family": "Grok 4",
    "status": "Voting tracked",
    "logo": "",
    "color": "#111111",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Grok 4.7 is tracked in Zorix Metron WebDev community voting. A community score is published; no request-volume observation is published here, and no request count is inferred.",
    "docs": "https://x.ai/news/grok-4-7",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-09-21",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting; request observation pending + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-09-21",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 55700000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Grok 4.7",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "nemotron-35-lightning",
    "name": "NVIDIA Nemotron 3.5 Lightning",
    "provider": "NVIDIA",
    "family": "Nemotron 3.5",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/nvidia.svg",
    "color": "#74B71B",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "NVIDIA Nemotron 3.5 Lightning is tracked in Zorix Metron WebDev community voting. A community score is published; no request-volume observation is published here, and no request count is inferred.",
    "docs": "https://blogs.nvidia.com/blog/nemotron-lightning-switchyard-rtx-dgx/",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "2026-08-11",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting; request observation pending + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "2026-08-11",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 2750000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "NVIDIA Nemotron 3.5 Lightning",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "nex-coder-4-plutos-preview",
    "name": "Nex Coder 4 Plutos Preview",
    "provider": "Zorix",
    "family": "Nex Coder 4",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/zorix.svg",
    "color": "#2563EB",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Nex Coder 4 Plutos Preview is tracked in Zorix Metron WebDev community voting. No request-volume observation is published here, and no request count is inferred.",
    "docs": "",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 96800000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Nex Coder 4 Plutos",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "glm-53",
    "name": "GLM 5.3",
    "provider": "Z.ai",
    "family": "GLM 5.3",
    "status": "Voting tracked",
    "logo": "/number-of-calls/assets/logos/glm.svg",
    "color": "#8B5CF6",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "GLM 5.3 is tracked in Zorix Metron WebDev community voting. No request-volume observation is published here, and no request count is inferred.",
    "docs": "",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 9800000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "GLM 5.3",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "qwen-38-omni-flash",
    "name": "Qwen 3.8 Omni Flash",
    "provider": "Alibaba",
    "family": "Qwen 3.8",
    "status": "Voting tracked",
    "logo": "",
    "color": "#111111",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Qwen 3.8 Omni Flash is tracked in Zorix Metron WebDev community voting. No request-volume observation is published here, and no request count is inferred.",
    "docs": "",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 8600000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Qwen 3.8 Omni Flash",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "mistral-large-3",
    "name": "Mistral Large 3",
    "provider": "Mistral AI",
    "family": "Mistral Large",
    "status": "Voting tracked",
    "logo": "",
    "color": "#111111",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Mistral Large 3 is tracked in Zorix Metron WebDev community voting. No request-volume observation is published here, and no request count is inferred.",
    "docs": "",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 1840000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Mistral Large 3",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  },
  {
    "id": "mistral-medium-35",
    "name": "Mistral Medium 3.5",
    "provider": "Mistral AI",
    "family": "Mistral Medium",
    "status": "Voting tracked",
    "logo": "",
    "color": "#111111",
    "dailyTokens": 0,
    "weeklyTokens": 0,
    "weeklyEstimated": true,
    "context": "—",
    "parameters": "Undisclosed",
    "activeParameters": "Undisclosed",
    "architecture": "Undisclosed",
    "inputPrice": "—",
    "outputPrice": "—",
    "about": "Mistral Medium 3.5 is tracked in Zorix Metron WebDev community voting. No request-volume observation is published here, and no request count is inferred.",
    "docs": "",
    "usageMetric": "community_votes",
    "weeklyRequests": null,
    "thirtyDayRequests": null,
    "launchDate": "",
    "underlyingModel": "",
    "blindTest": false,
    "guessUrl": "",
    "guessQuestion": "",
    "source": "Zorix Metron community voting + Zorix Metron supplied 30-day token observation",
    "includeInTokenRanking": true,
    "weeklyOnlyTokens": false,
    "dailyOnlyTokens": false,
    "fiveHourTokens": null,
    "fiveHourOnlyTokens": false,
    "providerReleaseDate": "",
    "maxInputTokens": "",
    "thirdPartyEvidence": [],
    "thirtyDayTokens": 1220000000000,
    "thirtyDayObserved": true,
    "thirtyDayOnlyTokens": true,
    "thirtyDayLabel": "Mistral Medium 3.5",
    "thirtyDayPeriodLabel": "30 days",
    "officialModelId": "",
    "knowledgeCutoff": "",
    "maxOutputTokens": "",
    "reasoningEfforts": [],
    "cachedInputPrice": "",
    "chart": []
  }
];
